version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: u6x5qhup
      POSTGRES_DB: housing_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./housing-api
    container_name: api-1
    restart: always
    depends_on:
      - db
      - model
    ports:
      - "8000:8000"

  model:
    build:
      context: ./housing-model
    container_name: model-1
    restart: always
    volumes:
      - ./housing-model/mlruns:/app/mlruns
    ports:
      - "8001:8001"
    environment:
      MLFLOW_TRACKING_URI: "file:///app/mlruns"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8001/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
