
services:
  db:
    image: postgres:15
    container_name: db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: u6x5qhup
      POSTGRES_DB: housing_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./housing-api
    container_name: api-1
    restart: always
    depends_on:
      - db
      - mlflow-model
    ports:
      - "8000:8000"

  mlflow-model:
    image: housing-mlflow-model:latest
    container_name: mlflow-model-1
    restart: always
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8001/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
