"""Create houses table

Revision ID: eee0a9c54649
Revises: 
Create Date: 2025-01-26 18:53:24.321553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee0a9c54649'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('houses', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('houses', 'housing_median_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('houses', 'total_rooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('houses', 'total_bedrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('houses', 'population',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('houses', 'households',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('houses', 'median_income',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('houses', 'median_house_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('houses', 'ocean_proximity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.alter_column('houses', 'ocean_proximity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('houses', 'median_house_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('houses', 'median_income',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('houses', 'households',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('houses', 'population',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('houses', 'total_bedrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('houses', 'total_rooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('houses', 'housing_median_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('houses', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('houses', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
